### PR TITLE
add codeforces task 1214C

### PR DESCRIPTION
**Pull request by EldarKZ16**
add codeforces task 1214C

image

### CODE REVIEW

**Comment by gopalgoel19** [comment]
Please add screenshot for codeforces/A/1208a.cpp  as well

**Comment by EldarKZ16** [comment]
@gopalgoel19 Done
66125722-93c89100-e609-11e9-9a8f-60c22edc8435

**Comment by gopalgoel19** [comment]
Do you have more solutions to add?

**Comment by EldarKZ16** [comment]
At the moment, I don't have any other solutions

**Pull request merged**
